version: "3.7"
services:
  users.backend:
    build:
      context: backends/users.backend
  products.backend:
    build:
      context: backends/products.backend
  ocelot.api-gateway:
    build:
      context: api-gateways/ocelot.api-gateway
    ports:
      - 8081:80
    depends_on:
      - users.backend
      - products.backend
  krakend.api-gateway:
    image: devopsfaith/krakend:0.9.0
    volumes:
      - ./api-gateways/krakend.api-gateway:/etc/krakend
    command: run -d -c /etc/krakend/krakend.json
    ports:
      - 8082:80
  envoy.api-gateway:
    image: envoyproxy/envoy:latest
    volumes:
      - ./api-gateways/envoy.api-gateway:/etc/envoy/
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - 8083:80
      - 8084:8084

  
